<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>pose_estimator</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="todo@todo.com">todo</maintainer>
  <license>MIT</license>

  <!-- 3rd party -->
  <exec_depend>foxglove_msgs</exec_depend>
  <exec_depend>image_transport</exec_depend>
  <exec_depend>message_filters</exec_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>
  <exec_depend>python3-imutils-pip</exec_depend>
  <exec_depend>python-transforms3d-pip</exec_depend>
  <exec_depend>python-opencv-contrib-pip</exec_depend>
  <exec_depend>tf_transformations</exec_depend>

  <!-- Ours -->
  <exec_depend>bb_perception_msgs</exec_depend>
  <exec_depend>image_processing</exec_depend>
  <exec_depend>yolo_msgs</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
